### ISSUE TITLE
MIT OCW

### ISSUE THREAD

**Issue by justinhester** [justinhester/stem#71]
## Potential Courses
- [ ] http://ocw.mit.edu/courses/chemistry/5-112-principles-of-chemical-science-fall-2005/
- [ ] http://ocw.mit.edu/courses/mechanical-engineering/2-627-fundamentals-of-photovoltaics-fall-2011/index.htm
- [ ] http://ocw.mit.edu/courses/comparative-media-studies/cms-s60-technopanics-moral-panics-about-technology-spring-2013/
- [ ] http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-087-practical-programming-in-c-january-iap-2010/
- [ ] http://ocw.mit.edu/courses/mathematics/18-01sc-single-variable-calculus-fall-2010/
- [ ] http://ocw.mit.edu/courses/aeronautics-and-astronautics/16-06-principles-of-automatic-control-fall-2012/
- [ ] http://ocw.mit.edu/courses/writing-and-humanistic-studies/21w-035-science-writing-and-new-media-elements-of-science-writing-for-the-public-spring-2013/
- [ ] http://ocw.mit.edu/courses/special-programs/sp-775-d-lab-energy-spring-2011/
- [ ] http://ocw.mit.edu/courses/sloan-school-of-management/15-390-new-enterprises-spring-2013/
- [ ] http://ocw.mit.edu/courses/materials-science-and-engineering/3-37-welding-and-joining-processes-fall-2002/index.htm
- [ ] http://ocw.mit.edu/courses/brain-and-cognitive-sciences/9-35-sensation-and-perception-spring-2009/
- [ ] http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-931-development-of-inventions-and-creative-ideas-spring-2008/
- [ ] http://ocw.mit.edu/courses/aeronautics-and-astronautics/16-810-engineering-design-and-rapid-prototyping-january-iap-2007/index.htm
- [ ] http://ocw.mit.edu/courses/linguistics-and-philosophy/24-900-introduction-to-linguistics-fall-2012/index.htm
